export const PRODS_LIST_REQUEST = "PRODS_LIST_REQUEST";
export const PRODS_LIST_SUCCESS = "PRODS_LIST_SUCCESS";
export const PRODS_LIST_FAIL = "PRODS_LIST_FAIL";

export const PRODS_CREATE_REQUEST = "PRODS_CREATE_REQUEST";
export const PRODS_CREATE_SUCCESS = "PRODS_CREATE_SUCCESS";
export const PRODS_CREATE_FAIL = "PRODS_CREATE_FAIL";

export const PRODS_UPDATE_REQUEST = "PRODS_UPDATE_REQUEST";
export const PRODS_UPDATE_SUCCESS = "PRODS_UPDATE_SUCCESS";
export const PRODS_UPDATE_FAIL = "PRODS_UPDATE_FAIL";

export const PRODS_DELETE_REQUEST = "PRODS_DELETE_REQUEST";
export const PRODS_DELETE_SUCCESS = "PRODS_DELETE_SUCCESS";
export const PRODS_DELETE_FAIL = "PRODS_DELETE_FAIL";
